### ISSUE TITLE
software-engineering: no guidance that a regression claim needs a repro bracketing the version boundary

### ISSUE THREAD

**Issue by owenlamont** [owenlamont/agent_skills#41]
When a report claims *"this is a regression"*, the reproduction shipped with it has to be
run on **both** sides of the version boundary, with its exit code carrying the result.
No skill currently says so: `grep -riE 'regression|bisect|last good version'` across
`skills/*/SKILL.md` returns nothing.

`software-engineering` comes closest but does not cover it. *Diagnose before you change*
says:

> Reproduce the failure, or instrument the code until you can observe it, before changing
> anything.

That is about diagnosing your own failure before editing code. This is about the
**artifact handed to someone else** as evidence for a claim.

## What went wrong

I filed [unionai-oss/pandera#2444](https://github.com/unionai-oss/pandera/issues/2444),
claiming a 0.32.0 → 0.32.1 regression, with a PEP 723 repro script pinned to 0.32.1.

I *had* verified that 0.32.0 passes — but with a separate throwaway snippet, not by
running the script I shipped. The human asked whether flipping the pin made it pass. It
did not:

```
alias=,               camelCase input: pass
serialization_alias=, snake_case input: pass
serialization_alias=, camelCase input: pass

coerce() produces columns : ['dash_length']
EXIT: 1
```

All three checks passed, then the script died and exited `1` — reading as *"bug present"*
when the opposite was true. The cause:

```
AttributeError: 'PydanticModel' object has no attribute 'column_names'
```

`column_names` was **introduced by the very change that caused the regression**, so my
diagnostic line could not run on the older version. A maintainer's first move —
re-pinning to confirm the regression — would have hit a traceback and a contradictory
exit code, in a published issue.

## The generalisable trap

Not just "run it on both versions", but: **a repro that must run on both sides of a
boundary cannot touch API introduced by the offending change.** Guard such access
(`getattr(obj, "attr", None)`) and let the script stay quiet on the older version. That is
the part I would not have anticipated without hitting it.

## Suggested shape

In `software-engineering`, near *Verify, don't assert*:

> **A regression claim needs a repro that brackets it.** Run the same script against the
> last good version and the bad one, and make the exit code carry the result — `0` on the
> earlier version, non-zero on the reported one. Asserting the boundary in prose while
> only ever running the broken version leaves the reader's first move untested. Guard any
> API introduced by the offending change, or the script dies on the older version and
> reports a misleading result.

`human-collaboration` is the alternative home, since this is about evidence handed to a
reviewer — but the rule is a verification discipline rather than a presentation one, so
`software-engineering` reads like the better fit.

## Verification

After guarding the access, the same script now exits `0` on `pandera==0.32.0` and `1` on
`==0.32.1`. Checked by pulling the code block back out of the live issue and running that
published text against both pins with `uv run --refresh`. The filed issue has been
corrected and now shows both outputs.
